- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/debian bullseye stable
    state: present     

- name: Install Docker packages
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli 
      - containerd.io 
      - docker-compose-plugin

- name: Edit docker configs
  copy:
    content: |
      {
        "log-driver": "json-file",
        "log-opts": {
        "max-size": "210m",
        "max-file": "3"
        }
      }
    dest: /etc/docker/daemon.json
  notify:
    - restart docker 
